server:
  port: 8081

spring:
  application:
    name: serviceAuth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/1-auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    hikari:
      pool-name: serviceAuthHikariCP
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,circuitbreakers,retries
  endpoint:
    health:
      show-details: always

app:
  jwt:
    issuer: serviceAuth
    secret: "T1Yt9cV5yZ0R3Q0p4uHn8Aq2Lw7mN3sX6pB4dF1kJ9rE2tV8cH5qZ7yW0uM6nR3"
    access-token-expiration: 3600        # 1h
    refresh-token-expiration: 2592000    # 30j

  system:
    superuser:
      username: root
      email: root@univ.local
      password: "Root#123"
    admin:
      username: admin
      email: admin@univ.local
      password: "Admin#123"

# Configuration Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException
